### ISSUE TITLE
use of class name "row" conflicts with bootstrap default styles

### ISSUE THREAD

**Issue by eddit** [xkawi/react-auto-header-list#1]
Bootstrap used the class name "row" for the basis of it's grid. The "row" class has styles that work with Bootstrap "cols". Each have margins and negative margins that cancel each other out. As such, a "row" should never be a direct descendant of "row", however this occurs in react-auto-header-list, which causes very strange css effects.

I'd recommend a relative naming scheme for your classes, ex: change "row" to "rahl-row". Bad example ("rahl" sounds weird) but you get the idea.

**Comment by xkawi** [comment]
@eddit thanks for the issue report. Yes, you are right, it was my bad for forgetting to remove "row" class name. It is never meant to be there. So, it should be fixed now @ v1.0.4
cheers.
